// export default {
//   EDIT_FILE_CONTENTS: 'EDIT_FILE_CONTENTS',
//   SAVE_FILE: 'SAVE_FILE',
//   OPEN_FILE: 'OPEN_FILE',
// };

// export const NEW_WINDOW = "NEW_WINDOW";
// export const CLOSE_WINDOW = "CLOSE_WINDOW";
// export const SHOW_WINDOW = "SHOW_WINDOW";
// export const HIDE_WINDOW = "HIDE_WINDOW";

export const EDIT_FILE_CONTENTS = 'EDIT_FILE_CONTENTS';

export const OPEN_FILE = 'OPEN_FILE';
export const OPEN_FILE_CONTRACT = 'OPEN_FILE_CONTRACT';
export const OPEN_FILE_RANDOM = 'OPEN_FILE_RANDOM';
export const CLOSE_FILE = 'CLOSE_FILE';

export const SAVE = 'SAVE';
export const SAVE_AS = 'SAVE_AS';
export const NEW_DIRECTORY = 'NEW_DIRECTORY';
export const NEW_CONTRACT = 'NEW_CONTRACT';
export const NEW_FILE = 'NEW_FILE';

export const ADD_FOLDER_TO_WORKSPACE = 'ADD_FOLDER_TO_WORKSPACE';
export const ADD_FILE_TO_WORKSPACE = 'ADD_FILE_TO_WORKSPACE';
export const REMOVE_WORKSPACE_ITEM = 'REMOVE_WORKSPACE_ITEM';
export const UPDATE_WORKSPACE_ITEM = 'UPDATE_WORKSPACE_ITEM';
export const CLEAR_WORKSPACE = 'CLEAR_WORKSPACE';
export const CHANGE_MODE = 'CHANGE_MODE';
export const UPDATE_STATE = 'UPDATE_STATE';
export const IS_ACTION_DEPLOYED = 'IS_ACTION_DEPLOYED';
export const INPUT_ACTION = 'INPUT_ACTION';

// export const COLLAPSE_DIRECTORY = "COLLAPSE_DIRECTORY";
// export const EXPAND_DIRECTORY = "EXPAND_DIRECTORY";
// export const DELETE_DIRECTORY = "DELETE_DIRECTORY";
// export const DELETE_FILE = "DELETE_FILE";

export const SHOW_FILE_IN_EDITOR = 'SHOW_FILE_IN_EDITOR';

// export const BEGIN_UNSAVED_CHANGES = "BEGIN_UNSAVED_CHANGES";
// export const END_UNSAVED_CHANGES = "END_UNSAVED_CHANGES";

export const GET_STATE = 'GET_STATE';
export const EDITOR_CHANGE = 'EDITOR_CHANGE';

export const PROJECT_FILESYSTEM_CHANGE = 'PROJECT_FILESYSTEM_CHANGE';

export const LOG_CONSOLE_OUTPUT = 'LOG_CONSOLE_OUTPUT';
export const SET_WALLET_STATUS = 'SET_WALLET_STATUS';

export const CREATE_ACCOUNT_NAME = 'CREATE_ACCOUNT_NAME';
export const CLOSE_CREATE_ACCOUNT_MODAL = 'CLOSE_CREATE_ACCOUNT_MODAL';
export const SHOW_CREATE_ACCOUNT_MODAL = 'SHOW_CREATE_ACCOUNT_MODAL';
export const SHOW_CONNECT_ACCOUNT_MODAL = 'SHOW_CONNECT_ACCOUNT_MODAL';
export const SHOW_CONFIGURE_NETWORK_MODAL = 'SHOW_CONFIGURE_NETWORK_MODAL';
export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL';
export const CONNECT_ACCOUNT = 'CONNECT_ACCOUNT';
export const CONFIGURE_NETWORK = 'CONFIGURE_NETWORK';

export const CLOSE_SELECT_WALLET_MODAL = 'CLOSE_SELECT_WALLET_MODAL';
export const SHOW_SELECT_WALLET_MODAL = 'SHOW_SELECT_WALLET_MODAL';
export const SHOW_AND_POPULATE_SELECT_WALLET_MODAL = 'SHOW_AND_POPULATE_SELECT_WALLET_MODAL';
export const SET_ACTIVE_WALLET = 'SET_ACTIVE_WALLET';
export const POPULATE_WALLET_LIST = 'POPULATE_WALLET_LIST';
